export const GETRECIPESUCESS = "GETRECIPESUCESS";
export const GETRECIPEFAILED = "GETRECIPEFAILED";
export const GETRECIPELODING = "GETRECIPELODING";
export const GETONERECIPESUCESS = "GETONERECIPESUCESS";
export const GETONERECIPEFAILED = "GETONERECIPEFAILED";
export const GETONERECIPELODING = "GETONERECIPELODING";

